/**
 * Conteúdo oficial: Autoavaliação do Agente de Contratação e Pregoeiro.
 * Fonte: instrumento autoral fornecido, versão 2.0, 23 de julho de 2026.
 */
window.DIAGNOSTIC_DATA = {
  projectName: "francisneyliberato-agente-contratacao-pregoeiro",
  title: "Autoavaliação do Agente de Contratação e Pregoeiro",
  subtitle: "50 questões situacionais | Lei nº 14.133/2021",
  accessCode: "francisneyliberato",
  scale: [
    { value: "1", short: "A", description: "Conduta A da questão: 1 ponto." },
    { value: "2", short: "B", description: "Conduta B da questão: 2 pontos." },
    { value: "3", short: "C", description: "Conduta C da questão: 3 pontos." },
    { value: "4", short: "D", description: "Conduta D da questão: 4 pontos." },
    { value: "5", short: "E", description: "Conduta E da questão: 5 pontos." }
  ],
  maturityLevels: [
    { min: 0, max: 35.9999, name: "Zona crítica", color: "#ef5c67", diagnosis: "A pontuação revela necessidade de intervenção prioritária antes da atuação em casos de maior complexidade.", recommendation: "Reavaliar a alocação em casos complexos e instituir desenvolvimento acompanhado." },
    { min: 36, max: 51.9999, name: "Zona de atenção", color: "#f08a4b", diagnosis: "Há lacunas relevantes que exigem supervisão, capacitação intensiva e controles adicionais.", recommendation: "Implantar supervisão, capacitação dirigida e checklists de decisão." },
    { min: 52, max: 67.9999, name: "Desenvolvimento necessário", color: "#f3bd4f", diagnosis: "O desempenho demanda um plano formal, concentrado nas três dimensões de menor resultado.", recommendation: "Executar plano de desenvolvimento de 30, 60 e 90 dias com evidências e metas." },
    { min: 68, max: 83.9999, name: "Desempenho consistente", color: "#55c7a4", diagnosis: "A atuação é segura, com oportunidade de sistematizar práticas e consolidar dimensões abaixo de 21 pontos.", recommendation: "Padronizar práticas, compartilhar aprendizados e consolidar as dimensões prioritárias." },
    { min: 84, max: 100, name: "Alta performance consolidada", color: "#52bfe6", diagnosis: "A atuação demonstra maturidade, segurança decisória e potencial para multiplicar boas práticas.", recommendation: "Atuar como multiplicador, manter revisão independente e monitorar complacência." }
  ],
  axes: [
    {
      id: 1, name: "INTEGRIDADE, ÉTICA E ORIENTAÇÃO AO INTERESSE PÚBLICO", short: "INTEGRIDADE", icon: "shield-check",
      recommendation: "Fortaleça registros, independência e decisões orientadas ao interesse público.", owner: "Agente de contratação / autoridade competente",
      questions: [
        q(1, "Ao perceber tentativa de influência indevida sobre uma decisão, você:", [{"letter":"A","text":"Atende ao pedido se não identificar prejuízo financeiro imediato."},{"letter":"B","text":"Recusa verbalmente, mas não registra o ocorrido."},{"letter":"C","text":"Afasta-se informalmente do caso, sem indicar a razão."},{"letter":"D","text":"Recusa, preserva registros e comunica à autoridade competente."},{"letter":"E","text":"Mantém independência, registra fatos objetivamente, protege evidências, declara eventual conflito e aciona os canais institucionais adequados."}], 1),
        q(2, "Quando possui relação pessoal com representante de empresa interessada, você:", [{"letter":"A","text":"Prossegue normalmente, pois acredita ser imparcial."},{"letter":"B","text":"Evita contato direto, mas permanece decidindo."},{"letter":"C","text":"Comenta a situação apenas com um colega."},{"letter":"D","text":"Informa formalmente a situação e solicita avaliação da autoridade."},{"letter":"E","text":"Declara tempestivamente o potencial conflito, não pratica atos decisórios enquanto pendente a avaliação e cumpre a solução institucional documentada."}], 1),
        q(3, "Para você, uma licitação bem-sucedida é aquela que:", [{"letter":"A","text":"Termina no menor prazo possível."},{"letter":"B","text":"Não recebe impugnações ou recursos."},{"letter":"C","text":"Obtém o menor preço nominal."},{"letter":"D","text":"Seleciona proposta válida, competitiva e vantajosa."},{"letter":"E","text":"Gera resultado público mensurável, com isonomia, competição, preço compatível, qualidade, riscos controlados e execução sustentável."}], 1),
        q(4, "Na publicidade dos atos e na proteção de informações, você:", [{"letter":"A","text":"Publica tudo, inclusive dados pessoais e informações sensíveis."},{"letter":"B","text":"Restringe documentos por cautela, sem análise específica."},{"letter":"C","text":"Segue apenas o padrão usado em processos anteriores."},{"letter":"D","text":"Distingue informações públicas, pessoais e temporariamente sigilosas."},{"letter":"E","text":"Aplica publicidade como regra, fundamenta restrições, protege dados pessoais e segredos legalmente tutelados e assegura rastreabilidade do acesso."}], 1),
        q(5, "Ao identificar erro próprio capaz de alterar o resultado, você:", [{"letter":"A","text":"Mantém a decisão para preservar sua autoridade."},{"letter":"B","text":"Corrige apenas se algum licitante questionar."},{"letter":"C","text":"Comunica informalmente à chefia e aguarda."},{"letter":"D","text":"Reconhece o erro, avalia seus efeitos e promove a correção cabível."},{"letter":"E","text":"Age com transparência, preserva contraditório e segurança jurídica, corrige o ato na extensão necessária e registra causas e controles preventivos."}], 1)
      ]
    },
    {
      id: 2, name: "PAPÉIS, GOVERNANÇA, SEGREGAÇÃO E CONTROLES", short: "PAPÉIS", icon: "network",
      recommendation: "Formalize papéis, controles compensatórios e rotinas de governança.", owner: "Agente de contratação / gestão",
      questions: [
        q(6, "Na distribuição de atribuições entre agente, equipe de apoio e área técnica, você:", [{"letter":"A","text":"Centraliza as tarefas para assegurar rapidez."},{"letter":"B","text":"Delega informalmente, conforme a disponibilidade."},{"letter":"C","text":"Distribui tarefas, mas não registra responsabilidades."},{"letter":"D","text":"Define papéis e confirma entregas e prazos."},{"letter":"E","text":"Formaliza papéis compatíveis com competências, estabelece pontos de controle, canais de escalonamento e mantém a responsabilidade decisória no agente competente."}], 1),
        q(7, "Quando a segregação plena de funções é inviável, você:", [{"letter":"A","text":"Ignora a questão por falta de pessoal."},{"letter":"B","text":"Registra genericamente a limitação."},{"letter":"C","text":"Solicita autorização para acumular todas as funções."},{"letter":"D","text":"Mapeia acumulações críticas e propõe controles compensatórios."},{"letter":"E","text":"Avalia risco, justifica a configuração, institui revisão independente ou controles compensatórios proporcionais e monitora sua efetividade."}], 1),
        q(8, "Diante de orientação divergente entre áreas técnica e jurídica, você:", [{"letter":"A","text":"Escolhe a posição que facilite a conclusão do processo."},{"letter":"B","text":"Adota automaticamente a posição jurídica."},{"letter":"C","text":"Adota automaticamente a posição técnica."},{"letter":"D","text":"Delimita competências e solicita fundamentos complementares."},{"letter":"E","text":"Integra fatos técnicos e enquadramento jurídico, registra divergências, decide no limite de sua competência e encaminha à autoridade o que exceder sua alçada."}], 1),
        q(9, "Sobre a matriz de riscos e os controles da contratação, você:", [{"letter":"A","text":"Considera a matriz um documento meramente formal."},{"letter":"B","text":"Reaproveita matriz de processo anterior sem adaptação."},{"letter":"C","text":"Lista riscos, mas não define tratamento."},{"letter":"D","text":"Define riscos, controles, responsáveis e prazos."},{"letter":"E","text":"Vincula riscos a objetivos e etapas, avalia probabilidade e impacto, define resposta, responsável, indicador, risco residual e monitora os controles."}], 1),
        q(10, "Em relação às linhas de defesa previstas na Lei nº 14.133/2021, você:", [{"letter":"A","text":"Entende que o controle é responsabilidade exclusiva da auditoria."},{"letter":"B","text":"Consulta o controle interno somente após problema grave."},{"letter":"C","text":"Envia todos os atos para revisão, transferindo a responsabilidade."},{"letter":"D","text":"Reconhece seu papel de primeira linha e aciona apoio quando necessário."},{"letter":"E","text":"Exerce autocontrole permanente, documenta decisões, coopera com assessoramento e controle e utiliza recomendações para aperfeiçoar a governança."}], 1)
      ]
    },
    {
      id: 3, name: "PLANEJAMENTO DA CONTRATAÇÃO E VISÃO SISTÊMICA", short: "PLANEJAMENTO DA CONTRATAÇÃO ", icon: "route",
      recommendation: "Aprimore o planejamento, ETP, TR e a estratégia da contratação.", owner: "Área demandante / agente de contratação",
      questions: [
        q(11, "Ao receber demanda com objeto genérico, você:", [{"letter":"A","text":"Publica com a descrição recebida para não atrasar."},{"letter":"B","text":"Corrige sozinho a descrição e prossegue."},{"letter":"C","text":"Solicita apenas quantidades e prazo."},{"letter":"D","text":"Devolve com orientações e verifica PCA e orçamento."},{"letter":"E","text":"Conduz diagnóstico com a área demandante, valida necessidade, resultados, riscos, mercado, PCA, orçamento e estratégia antes de definir a solução."}], 1),
        q(12, "Na análise do Estudo Técnico Preliminar, você:", [{"letter":"A","text":"Confere somente assinatura e existência do documento."},{"letter":"B","text":"Verifica se todos os campos foram preenchidos."},{"letter":"C","text":"Compara com modelos de contratações anteriores."},{"letter":"D","text":"Examina alternativas, quantitativos, requisitos e justificativa."},{"letter":"E","text":"Testa criticamente necessidade, alternativas, ciclo de vida, parcelamento, sustentabilidade, riscos, viabilidade e resultados pretendidos."}], 1),
        q(13, "Ao definir quantitativos, você:", [{"letter":"A","text":"Repete a quantidade da contratação anterior."},{"letter":"B","text":"Aceita a estimativa da área sem memória de cálculo."},{"letter":"C","text":"Utiliza consumo histórico isoladamente."},{"letter":"D","text":"Combina histórico, demanda projetada e justificativas."},{"letter":"E","text":"Valida dados, sazonalidade, estoques, contratos vigentes, expansão, perdas e cenários, documentando memória de cálculo e risco de excesso ou falta."}], 1),
        q(14, "Sobre parcelamento ou agrupamento do objeto, você:", [{"letter":"A","text":"Agrupa tudo para facilitar a gestão."},{"letter":"B","text":"Parcela sempre para aumentar o número de itens."},{"letter":"C","text":"Repete a estrutura do edital anterior."},{"letter":"D","text":"Analisa mercado, economia de escala e viabilidade técnica."},{"letter":"E","text":"Fundamenta a decisão com divisibilidade, competição, mercado, custos de gestão, integração, economia de escala e riscos de execução."}], 1),
        q(15, "Na incorporação de sustentabilidade, você:", [{"letter":"A","text":"Não inclui requisitos para evitar restrição à competição."},{"letter":"B","text":"Inclui cláusula genérica de sustentabilidade."},{"letter":"C","text":"Copia exigências de outro processo."},{"letter":"D","text":"Seleciona requisitos pertinentes ao objeto e ao mercado."},{"letter":"E","text":"Adota critérios proporcionais e verificáveis no ciclo de vida, avaliando impactos ambiental, social e econômico sem criar barreira indevida."}], 1)
      ]
    },
    {
      id: 4, name: "PESQUISA DE PREÇOS, MERCADO E ESTRATÉGIA COMPETITIVA", short: "PESQUISA DE PREÇOS", icon: "badge-dollar-sign",
      recommendation: "Qualifique a pesquisa de preços e a análise de mercado.", owner: "Agente de contratação / equipe de planejamento",
      questions: [
        q(16, "Quando a pesquisa de preços apresenta grande dispersão, você:", [{"letter":"A","text":"Usa automaticamente a média de todos os valores."},{"letter":"B","text":"Seleciona os menores preços."},{"letter":"C","text":"Exclui extremos sem registrar justificativa."},{"letter":"D","text":"Complementa a pesquisa e registra a metodologia."},{"letter":"E","text":"Analisa fontes, condições comerciais, outliers, memória de cálculo e comparabilidade, justificando método e preço estimado."}], 1),
        q(17, "Ao realizar análise de mercado, você:", [{"letter":"A","text":"Limita-se a consultar três fornecedores."},{"letter":"B","text":"Pesquisa somente contratações do próprio órgão."},{"letter":"C","text":"Consulta bases públicas, sem interpretar o mercado."},{"letter":"D","text":"Mapeia fornecedores, soluções e práticas comerciais."},{"letter":"E","text":"Analisa estrutura, competição, concentração, inovação, capacidade, barreiras, sazonalidade e práticas de preço para orientar requisitos e estratégia."}], 1),
        q(18, "Na definição do orçamento sigiloso, quando juridicamente admissível, você:", [{"letter":"A","text":"Adota sempre para pressionar preços."},{"letter":"B","text":"Nunca adota, por entender que tudo deve ser público."},{"letter":"C","text":"Segue a preferência pessoal da chefia."},{"letter":"D","text":"Avalia vantagens e riscos para o caso concreto."},{"letter":"E","text":"Fundamenta a decisão com mercado, assimetria de informação, competição e risco, preserva o sigilo até o momento legal e assegura acesso aos órgãos de controle."}], 1),
        q(19, "Na escolha do modo de disputa, você:", [{"letter":"A","text":"Repete o formato da última licitação."},{"letter":"B","text":"Adota sempre o modo aberto."},{"letter":"C","text":"Escolhe apenas pela funcionalidade do sistema."},{"letter":"D","text":"Considera objeto, mercado e risco competitivo."},{"letter":"E","text":"Fundamenta com dados de mercado, natureza do objeto, formação de preços, competitividade, risco de conluio e resultado esperado."}], 1),
        q(20, "Antes de publicar, você avalia potencial restrição à competição:", [{"letter":"A","text":"Somente se houver impugnação."},{"letter":"B","text":"Contando o número de empresas consultadas."},{"letter":"C","text":"Comparando o edital com modelo anterior."},{"letter":"D","text":"Revendo requisitos técnicos e de habilitação."},{"letter":"E","text":"Testando cada exigência quanto a necessidade, proporcionalidade, oferta no mercado, impacto competitivo e possibilidade de solução menos restritiva."}], 1)
      ]
    },
    {
      id: 5, name: "EDITAL, TERMO DE REFERÊNCIA E MODELAGEM DO CERTAME", short: "EDITAL", icon: "file-check-2",
      recommendation: "Faça revisão cruzada dos artefatos e dos critérios do edital.", owner: "Agente de contratação / assessoria jurídica",
      questions: [
        q(21, "Ao revisar a coerência entre ETP, TR e edital, você:", [{"letter":"A","text":"Confere apenas nomes e datas."},{"letter":"B","text":"Verifica se todos os documentos estão assinados."},{"letter":"C","text":"Analisa os documentos separadamente."},{"letter":"D","text":"Compara objeto, quantidades, critérios e obrigações."},{"letter":"E","text":"Executa revisão cruzada de necessidade, solução, requisitos, medição, pagamento, sanções, riscos, prazos, habilitação e critérios de julgamento."}], 1),
        q(22, "Na definição de exigências de habilitação, você:", [{"letter":"A","text":"Inclui todas as certidões possíveis."},{"letter":"B","text":"Repete exigências do edital anterior."},{"letter":"C","text":"Usa modelos padronizados sem análise do objeto."},{"letter":"D","text":"Seleciona requisitos necessários e previstos em lei."},{"letter":"E","text":"Justifica exigências proporcionais à complexidade e ao risco, evita duplicidades e restrições e define meios objetivos de comprovação."}], 1),
        q(23, "Quando prevê prova de conceito, amostra ou teste, você:", [{"letter":"A","text":"Exige de todos os participantes antes dos lances."},{"letter":"B","text":"Define apenas que haverá avaliação."},{"letter":"C","text":"Deixa os critérios para a equipe técnica decidir na sessão."},{"letter":"D","text":"Estabelece critérios, responsáveis e procedimento no edital."},{"letter":"E","text":"Define finalidade, momento, convocação, critérios objetivos, ambiente, prazos, documentação, contraditório, destino de amostras e consequências do resultado."}], 1),
        q(24, "Sobre minuta contratual, medição e pagamento, você:", [{"letter":"A","text":"Considera assunto exclusivo da gestão do contrato."},{"letter":"B","text":"Utiliza cláusulas genéricas."},{"letter":"C","text":"Copia minuta de objeto semelhante."},{"letter":"D","text":"Verifica obrigações, níveis de serviço e pagamento."},{"letter":"E","text":"Alinha entregas, indicadores, aceite, medição, glosas, pagamento, reajuste, garantias, sanções e matriz de riscos ao resultado pretendido."}], 1),
        q(25, "Diante de impugnação que revela falha relevante no edital, você:", [{"letter":"A","text":"Indefere para preservar o cronograma."},{"letter":"B","text":"Corrige silenciosamente sem republicar."},{"letter":"C","text":"Responde que o edital segue modelo oficial."},{"letter":"D","text":"Reconhece a falha e avalia necessidade de retificação."},{"letter":"E","text":"Analisa mérito sem defensividade, corrige o instrumento, republica e reabre prazo quando a alteração afetar propostas, registrando impacto e prevenção."}], 1)
      ]
    },
    {
      id: 6, name: "CONDUÇÃO DA SESSÃO, LANCES E JULGAMENTO", short: "CONDUÇÃO DA SESSÃO", icon: "gavel",
      recommendation: "Padronize a condução da sessão e a motivação das decisões.", owner: "Pregoeiro / agente de contratação",
      questions: [
        q(26, "Durante sessão, surge dúvida complexa sob pressão de tempo. Você:", [{"letter":"A","text":"Responde imediatamente, mesmo sem segurança."},{"letter":"B","text":"Ignora a questão e prossegue."},{"letter":"C","text":"Suspende sem explicar o motivo."},{"letter":"D","text":"Informa a análise e registra eventual suspensão."},{"letter":"E","text":"Mantém serenidade, delimita a dúvida, consulta autos e regras, comunica com transparência e decide motivadamente, preservando a igualdade."}], 1),
        q(27, "Quando o sistema apresenta instabilidade relevante, você:", [{"letter":"A","text":"Prossegue para cumprir o cronograma."},{"letter":"B","text":"Orienta licitantes a tentarem novamente."},{"letter":"C","text":"Suspende informalmente sem registrar."},{"letter":"D","text":"Avalia impacto e comunica providências."},{"letter":"E","text":"Verifica alcance e prejuízo, preserva registros, suspende ou reabre quando necessário e assegura tratamento isonômico com motivação documentada."}], 1),
        q(28, "Diante de proposta com aparente erro de preenchimento, você:", [{"letter":"A","text":"Desclassifica imediatamente."},{"letter":"B","text":"Corrige o valor por conta própria."},{"letter":"C","text":"Permite alteração ampla da proposta."},{"letter":"D","text":"Abre diligência para esclarecer a falha."},{"letter":"E","text":"Distingue erro sanável de alteração substancial, preserva isonomia e vinculação, diligencia e registra fundamentos e limites do saneamento."}], 1),
        q(29, "Quando há indício de inexequibilidade, você:", [{"letter":"A","text":"Desclassifica automaticamente."},{"letter":"B","text":"Aceita declaração simples do fornecedor."},{"letter":"C","text":"Solicita planilha sem examinar coerência."},{"letter":"D","text":"Abre diligência e analisa justificativas."},{"letter":"E","text":"Realiza diligência proporcional, confronta custos, produtividade, tributos, riscos e evidências, assegura manifestação e decide motivadamente."}], 1),
        q(30, "Na desclassificação de proposta, você:", [{"letter":"A","text":"Registra apenas “não atende ao edital”."},{"letter":"B","text":"Copia a cláusula sem relacioná-la aos fatos."},{"letter":"C","text":"Apresenta justificativa breve no sistema."},{"letter":"D","text":"Indica fatos, cláusula e fundamento."},{"letter":"E","text":"Expõe evidências, aplica edital e norma ao caso, avalia saneamento, observa proporcionalidade e produz conclusão clara e controlável."}], 1)
      ]
    },
    {
      id: 7, name: "HABILITAÇÃO, DILIGÊNCIAS E SANEAMENTO", short: "HABILITAÇÃO", icon: "files",
      recommendation: "Aplique diligências proporcionais, isonomia e formalismo moderado.", owner: "Pregoeiro / equipe de apoio",
      questions: [
        q(31, "Sobre formalismo moderado, você:", [{"letter":"A","text":"Rejeita qualquer documento com erro."},{"letter":"B","text":"Aceita toda correção para ampliar a competição."},{"letter":"C","text":"Decide sem critérios consistentes."},{"letter":"D","text":"Admite correção que não altere substância nem gere vantagem."},{"letter":"E","text":"Distingue falha formal de requisito material, aplica isonomia, competitividade e verdade material e fundamenta limites e diligências."}], 1),
        q(32, "Ao consultar cadastro ou sistema oficial de fornecedores, você:", [{"letter":"A","text":"Confia apenas na declaração do licitante."},{"letter":"B","text":"Consulta o sistema, mas não registra evidência."},{"letter":"C","text":"Imprime todas as telas sem selecionar o relevante."},{"letter":"D","text":"Verifica dados pertinentes e junta comprovação."},{"letter":"E","text":"Confere situação no momento adequado, preserva evidência datada, cruza documentos necessários e trata indisponibilidade do sistema de forma isonômica."}], 1),
        q(33, "Se documento comprova condição preexistente, mas foi apresentado com falha, você:", [{"letter":"A","text":"Recusa qualquer complementação."},{"letter":"B","text":"Aceita documento produzido depois da sessão, sem exame."},{"letter":"C","text":"Solicita novo documento sem explicar o objetivo."},{"letter":"D","text":"Diligencia para comprovar a condição existente na data exigida."},{"letter":"E","text":"Delimita o fato a comprovar, impede criação posterior de requisito inexistente, assegura igualdade e motiva a aceitação ou rejeição da prova."}], 1),
        q(34, "Na análise de qualificação técnica, você:", [{"letter":"A","text":"Exige experiência idêntica ao objeto integral."},{"letter":"B","text":"Aceita qualquer atestado genérico."},{"letter":"C","text":"Avalia apenas quantidade de atestados."},{"letter":"D","text":"Verifica parcelas relevantes e compatibilidade."},{"letter":"E","text":"Examina pertinência, complexidade, quantitativos legalmente admissíveis, somatório quando cabível, autenticidade e proporcionalidade das exigências."}], 1),
        q(35, "Diante de dúvida sobre autenticidade documental, você:", [{"letter":"A","text":"Presume fraude e inabilita."},{"letter":"B","text":"Ignora para evitar atraso."},{"letter":"C","text":"Solicita declaração do próprio licitante."},{"letter":"D","text":"Realiza verificação em fonte idônea."},{"letter":"E","text":"Preserva contraditório, verifica emissores e bases oficiais, documenta evidências, decide o certame e encaminha possível ilícito à autoridade competente."}], 1)
      ]
    },
    {
      id: 8, name: "NEGOCIAÇÃO, RECURSOS E GESTÃO DE INCIDENTES", short: "NEGOCIAÇÃO", icon: "messages-square",
      recommendation: "Estruture negociação, recursos e gestão documentada de incidentes.", owner: "Pregoeiro / autoridade competente",
      questions: [
        q(36, "Na negociação com o primeiro colocado, você:", [{"letter":"A","text":"Solicita desconto genérico uma única vez."},{"letter":"B","text":"Insiste em preço inferior, mesmo inexequível."},{"letter":"C","text":"Aceita por estar abaixo do estimado."},{"letter":"D","text":"Utiliza referências e busca condição mais vantajosa."},{"letter":"E","text":"Planeja com dados, explora preço e condições admissíveis, preserva exequibilidade, registra argumentos e demonstra o ganho obtido."}], 1),
        q(37, "Ao decidir recurso administrativo, você:", [{"letter":"A","text":"Mantém a decisão para proteger sua autoridade."},{"letter":"B","text":"Encaminha sem análise própria."},{"letter":"C","text":"Responde apenas aos pontos mais simples."},{"letter":"D","text":"Reexamina fundamentos e argumentos essenciais."},{"letter":"E","text":"Exerce autocontrole imparcial, enfrenta argumentos capazes de alterar a conclusão, corrige eventual erro e encaminha decisão claramente motivada."}], 1),
        q(38, "Diante de possível conluio, você:", [{"letter":"A","text":"Nada faz sem prova definitiva."},{"letter":"B","text":"Acusa participantes no chat."},{"letter":"C","text":"Cancela imediatamente o certame."},{"letter":"D","text":"Preserva registros e comunica à autoridade."},{"letter":"E","text":"Identifica sinais objetivos, evita prejulgamento, protege evidências, adota providências processuais e encaminha aos órgãos competentes com sigilo adequado."}], 1),
        q(39, "Quando incidente pode exigir anulação ou revogação, você:", [{"letter":"A","text":"Decide sozinho para ganhar tempo."},{"letter":"B","text":"Continua o processo até ordem superior."},{"letter":"C","text":"Sugere cancelamento sem analisar consequências."},{"letter":"D","text":"Instrui os fatos e encaminha à autoridade competente."},{"letter":"E","text":"Distingue ilegalidade e mérito administrativo, avalia efeitos, contraditório, convalidação quando cabível e interesse público, apresentando motivação e alternativas à autoridade."}], 1),
        q(40, "Após certame com muitos incidentes, você:", [{"letter":"A","text":"Arquiva e inicia o próximo processo."},{"letter":"B","text":"Busca identificar quem errou."},{"letter":"C","text":"Comenta informalmente com a equipe."},{"letter":"D","text":"Registra lições e sugere ajustes."},{"letter":"E","text":"Conduz retrospectiva sem culpabilização, identifica causas, dados e controles, define ações, responsáveis e prazos e compartilha aprendizado institucional."}], 1)
      ]
    },
    {
      id: 9, name: "COMUNICAÇÃO, LIDERANÇA E INTELIGÊNCIA EMOCIONAL", short: "COMUNICAÇÃO", icon: "heart-handshake",
      recommendation: "Desenvolva comunicação, liderança e autorregulação sob pressão.", owner: "Pregoeiro / liderança da equipe",
      questions: [
        q(41, "Quando recebe crítica pública durante a sessão, você:", [{"letter":"A","text":"Responde no mesmo tom."},{"letter":"B","text":"Encerra a comunicação."},{"letter":"C","text":"Ignora mesmo que haja questão relevante."},{"letter":"D","text":"Responde objetivamente e mantém postura profissional."},{"letter":"E","text":"Regula a reação, separa conteúdo e forma, responde com firmeza respeitosa, esclarece o procedimento e registra o necessário."}], 1),
        q(42, "Na relação com a equipe de apoio, você:", [{"letter":"A","text":"Centraliza decisões e usa a equipe apenas operacionalmente."},{"letter":"B","text":"Delega tudo e intervém só no problema."},{"letter":"C","text":"Distribui tarefas sem confirmar responsabilidades."},{"letter":"D","text":"Define papéis, acompanha e ouve contribuições."},{"letter":"E","text":"Alinha propósito, papéis e critérios, cria segurança para alertas, acompanha pontos críticos e reconhece contribuições sem transferir responsabilidade."}], 1),
        q(43, "Sua comunicação no chat e nas atas é:", [{"letter":"A","text":"Improvisada e repleta de abreviações."},{"letter":"B","text":"Breve mesmo quando a decisão exige explicação."},{"letter":"C","text":"Extensa e excessivamente jurídica."},{"letter":"D","text":"Clara, objetiva e suficiente."},{"letter":"E","text":"Planejada, respeitosa, acessível e rastreável, com padrões para atos recorrentes e fundamentação individualizada nas decisões."}], 1),
        q(44, "Sob carga elevada de processos, você:", [{"letter":"A","text":"Trabalha sem priorização até concluir tudo."},{"letter":"B","text":"Prioriza apenas pelo prazo mais próximo."},{"letter":"C","text":"Transfere tarefas sem avaliar riscos."},{"letter":"D","text":"Organiza demandas por prazo, complexidade e risco."},{"letter":"E","text":"Mantém painel de capacidade, prioriza por risco e valor, negocia prazos, solicita apoio cedo e preserva qualidade decisória e saúde ocupacional."}], 1),
        q(45, "Após situação de alta tensão, você:", [{"letter":"A","text":"Leva a tensão para decisões seguintes."},{"letter":"B","text":"Evita rever o episódio."},{"letter":"C","text":"Procura culpados em conversas informais."},{"letter":"D","text":"Identifica acertos e melhorias."},{"letter":"E","text":"Realiza revisão pós-evento, reconhece gatilhos e causas, ajusta controles e pratica técnica de recuperação emocional."}], 1)
      ]
    },
    {
      id: 10, name: "DADOS, INOVAÇÃO, APRENDIZAGEM E MELHORIA CONTÍNUA", short: "DADOS", icon: "brain-circuit",
      recommendation: "Mantenha atualização normativa, indicadores e melhoria contínua.", owner: "Gestão / agente de contratação",
      questions: [
        q(46, "Sobre o uso de indicadores, você:", [{"letter":"A","text":"Não utiliza porque cada contratação é única."},{"letter":"B","text":"Acompanha somente número de certames."},{"letter":"C","text":"Observa prazo e desconto."},{"letter":"D","text":"Monitora prazo, competição, fracassos e economia."},{"letter":"E","text":"Usa painel equilibrado com tempo, competição, impugnações, diligências, fracassos, economia, qualidade, riscos e desempenho contratual."}], 1),
        q(47, "Quando norma ou regulamento é alterado, você:", [{"letter":"A","text":"Aguarda atualização dos modelos oficiais."},{"letter":"B","text":"Toma conhecimento apenas no caso concreto."},{"letter":"C","text":"Lê somente resumo de terceiros."},{"letter":"D","text":"Analisa o texto e comunica impactos."},{"letter":"E","text":"Mantém rotina de atualização, compara versões, identifica impactos em fluxos e modelos, valida interpretação e dissemina orientação."}], 1),
        q(48, "No uso de inteligência artificial ou automação, você:", [{"letter":"A","text":"Copia a resposta gerada sem revisão."},{"letter":"B","text":"Evita qualquer uso de tecnologia."},{"letter":"C","text":"Utiliza ferramenta pública com dados sensíveis."},{"letter":"D","text":"Usa para apoio, revisando conteúdo antes de decidir."},{"letter":"E","text":"Define finalidade e controles, protege dados, verifica fontes e vieses, mantém revisão humana, registra uso relevante e assume integralmente a decisão."}], 1),
        q(49, "Seu desenvolvimento profissional ocorre por:", [{"letter":"A","text":"Experiência diária sem plano."},{"letter":"B","text":"Cursos obrigatórios ocasionais."},{"letter":"C","text":"Leitura apenas quando surge dúvida."},{"letter":"D","text":"Plano anual com cursos e atualização."},{"letter":"E","text":"Plano contínuo baseado em lacunas, estudo deliberado, simulações, feedback, comunidade de prática, atualização normativa e metas verificáveis."}], 1),
        q(50, "Para demonstrar impacto da melhoria implantada, você:", [{"letter":"A","text":"Relata percepções positivas."},{"letter":"B","text":"Apresenta apenas economia estimada."},{"letter":"C","text":"Compara um processo antes e depois."},{"letter":"D","text":"Define indicadores e acompanha tendência."},{"letter":"E","text":"Estabelece linha de base, metas, indicadores de processo e resultado, método de coleta, responsáveis, periodicidade e prestação de contas à gestão."}], 1)
      ]
    }
  ],
  riskTriggers: []
};

function q(number, text, options, weight) {
  return { number, text, options, evidence: "Registre a evidência, providência ou aprendizado associado à resposta, quando pertinente.", weight };
}

